version: "2.6.1"

services:

  api:

    image: abcdeclair/server:1.0
    
    volumes:
      - /app/node_modules
      - ./server:/app

    ports:
      - 3333:3333

  client:

    image: phongsakorn/client:1.0
         
    volumes:
      - /app/node_modules
      - ./client:/app
      
    ports:
        - 3000:3000
