version: "2.6.1"

services:

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    
    volumes:
      - /app/node_modules
      - ./server:/app

    ports:
      - 3333:3333

  client:
    build:
      dockerfile:  Dockerfile
      context: "./client"
           
    volumes:
      - /app/node_modules
      - ./client:/app
      
    ports:
        - 3000:3000
